name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    
    - name: Setup yarn
      shell: bash
      run: |
        corepack enable
        yarn set version 3.6.0
        yarn plugin import workspace-tools

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: yarn

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable